version: '3'
services:
  tomcat:
    container_name: tomcat
    image: tomcat:9-jre8
    ports:
      - "8080:8080"
    volumes:
      - ./target/app.war:/usr/local/tomcat/webapps/app.war
      - ./lib/liblpsolve55j.so:/usr/local/tomcat/native-jni-lib/liblpsolve55j.so
      - ./lib/liblpsolve55.so:/usr/local/tomcat/native-jni-lib/liblpsolve55.so
    links:
      - modelStorage
      - metaInfo

  modelStorage:
    container_name: modelStorage
    image: postgres:11
    ports:
      - "5432"
    environment:
      POSTGRES_DB: modelStorage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_PORT: 5432
    volumes:
      - ./dump/modelStorage.sql:/docker-entrypoint-initdb.d/modelStorage.sql

  metaInfo:
    container_name: metaInfo
    image: postgres:11
    ports:
      - "5432"
    environment:
      POSTGRES_DB: metaInfo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_PORT: 5432
    volumes:
      - ./dump/metaInfo.sql:/docker-entrypoint-initdb.d/metaInfo.sql