version: '3'
services:
  tomcat:
    container_name: tomcat
    image: tomcat:9.0-jre8
    # build: ./
    ports:
      - "8080:8080"
    volumes:
      - ./target/app.war:/usr/local/tomcat/webapps/app.war
    links:
      - modelStorage
      - metaInfo

  modelStorage:
    container_name: modelStorage
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: modelStorage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./dump/modelStorage.sql:/docker-entrypoint-initdb.d/modelStorage.sql

  metaInfo:
    container_name: metaInfo
    image: postgres:11
    ports:
      - "5442:5432"
    environment:
      POSTGRES_DB: metaInfo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_PORT: 5432
    volumes:
      - ./dump/metaInfo.sql:/docker-entrypoint-initdb.d/metaInfo.sql
      # - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh